spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
  application:
    name: moviefun-app

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: <access key id>
  secretKey: <secret access key>
  bucketName: <name of the bucket>

albums:
  url: http://localhost:8081/albums
movies:
  url: http://localhost:8082/movies
